# docker-compose up --detach --scale master=1 --scale slave=2
# Write Down slave container mapped port( ex) 56782:3306) in src/main/resources/sharding.yml -> slave0, slave1 jdbcUrl
version: '3.1'
services:
  master:
    image: 'bitnami/mysql:latest'
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=
      - MYSQL_USER=user
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=LAB
      - MYSQL_ROOT_PASSWORD=
  slave:
    image: 'bitnami/mysql:latest'
    ports:
      - "3306"
    depends_on:
      - master
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=
      - MYSQL_MASTER_HOST=master
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_USER=user
      - MYSQL_PASSWORD=
      - MYSQL_MASTER_ROOT_PASSWORD=